export const colaboradoresMock = [
  { nombre: "Juan", apellido: "Pérez", direccion: "Zona 1, Ciudad", edad: 23 },
  { nombre: "María", apellido: "Gómez", direccion: "Zona 5, Ciudad", edad: 34 },
  { nombre: "Carlos", apellido: "Ramírez", direccion: "Zona 7, Ciudad", edad: 45 },
  { nombre: "Ana", apellido: "López", direccion: "Zona 10, Ciudad", edad: 29 },
  { nombre: "Luis", apellido: "Hernández", direccion: "Mixco", edad: 52 },
  { nombre: "Sofía", apellido: "Castillo", direccion: "Villa Nueva", edad: 21 },
  { nombre: "Diego", apellido: "Morales", direccion: "Zona 11, Ciudad", edad: 38 },
  { nombre: "Valeria", apellido: "Mendoza", direccion: "Zona 2, Ciudad", edad: 26 },
  { nombre: "José", apellido: "Cruz", direccion: "Zona 18, Ciudad", edad: 47 },
  { nombre: "Andrea", apellido: "Flores", direccion: "Zona 14, Ciudad", edad: 31 },

  { nombre: "Miguel", apellido: "Ortega", direccion: "Zona 6, Ciudad", edad: 55 },
  { nombre: "Daniela", apellido: "Reyes", direccion: "San Cristóbal", edad: 24 },
  { nombre: "Fernando", apellido: "Vásquez", direccion: "Zona 12, Ciudad", edad: 41 },
  { nombre: "Paola", apellido: "Navarro", direccion: "Zona 4, Ciudad", edad: 28 },
  { nombre: "Jorge", apellido: "Aguilar", direccion: "Zona 21, Ciudad", edad: 36 },
  { nombre: "Camila", apellido: "Rojas", direccion: "Zona 3, Ciudad", edad: 19 },
  { nombre: "Ricardo", apellido: "Fuentes", direccion: "Zona 8, Ciudad", edad: 50 },
  { nombre: "Lucía", apellido: "Pineda", direccion: "Zona 15, Ciudad", edad: 27 },
  { nombre: "Oscar", apellido: "Mejía", direccion: "Zona 9, Ciudad", edad: 44 },
  { nombre: "Natalia", apellido: "Chávez", direccion: "Zona 13, Ciudad", edad: 33 },

  { nombre: "Kevin", apellido: "Salazar", direccion: "Zona 17, Ciudad", edad: 22 },
  { nombre: "Fernanda", apellido: "Ibarra", direccion: "Zona 16, Ciudad", edad: 39 },
  { nombre: "Alejandro", apellido: "Soto", direccion: "Zona 20, Ciudad", edad: 48 },
  { nombre: "Gabriela", apellido: "Monroy", direccion: "Zona 1, Mixco", edad: 25 },
  { nombre: "Hugo", apellido: "Castañeda", direccion: "Zona 19, Ciudad", edad: 53 },
  { nombre: "Karen", apellido: "Alvarado", direccion: "Zona 6, Mixco", edad: 30 },
  { nombre: "Manuel", apellido: "Villalobos", direccion: "Zona 7, Mixco", edad: 42 },
  { nombre: "Andrea", apellido: "Quintana", direccion: "Zona 2, Mixco", edad: 27 },
  { nombre: "Pablo", apellido: "Escobar", direccion: "Zona 5, Mixco", edad: 46 },
  { nombre: "Laura", apellido: "Contreras", direccion: "Zona 10, Mixco", edad: 35 },

  { nombre: "Raúl", apellido: "Cabrera", direccion: "Zona 11, Mixco", edad: 51 },
  { nombre: "Elena", apellido: "Gutiérrez", direccion: "Zona 14, Mixco", edad: 29 },
  { nombre: "Sergio", apellido: "Barrios", direccion: "Zona 12, Mixco", edad: 40 },
  { nombre: "Monica", apellido: "Delgado", direccion: "Zona 8, Mixco", edad: 32 },
  { nombre: "Esteban", apellido: "Linares", direccion: "Zona 18, Mixco", edad: 49 },
  { nombre: "Rosa", apellido: "Peña", direccion: "Zona 9, Mixco", edad: 26 },
  { nombre: "Andrés", apellido: "Zelaya", direccion: "Zona 15, Mixco", edad: 37 },
  { nombre: "Patricia", apellido: "Corado", direccion: "Zona 3, Mixco", edad: 43 },
  { nombre: "Mauricio", apellido: "Lemus", direccion: "Zona 4, Mixco", edad: 54 },

  { nombre: "Isabel", apellido: "Fajardo", direccion: "Zona 13, Mixco", edad: 28 },
  { nombre: "Roberto", apellido: "Maldonado", direccion: "Zona 17, Mixco", edad: 45 },
  { nombre: "Silvia", apellido: "Palma", direccion: "Zona 16, Mixco", edad: 34 },
  { nombre: "Julio", apellido: "Portillo", direccion: "Zona 19, Mixco", edad: 52 },
  { nombre: "Diana", apellido: "Cifuentes", direccion: "Zona 20, Mixco", edad: 23 },
  { nombre: "Emilio", apellido: "Arévalo", direccion: "Zona 21, Mixco", edad: 41 },
  { nombre: "Claudia", apellido: "Bolaños", direccion: "Zona 22, Mixco", edad: 31 },
  { nombre: "Victor", apellido: "Samayoa", direccion: "Zona 23, Mixco", edad: 47 },
  { nombre: "Marvin", apellido: "Godínez", direccion: "Zona 24, Mixco", edad: 36 }
];